### PR TITLE
Fix rainfall slider

### PR DESCRIPTION
**Pull request by lambert3**

### CODE REVIEW

**Review by RonKbS — COMMENTED** [review]
@lambert3 , I do not see the fix for the rainfall slider.
Please restrict new changes to what the PR is about. 
Also, the districts and indicators were intentionally changed to reduce on the length of code in the applicationState.js file
If you have a linter that is automatically making changes to the files installed in your IDE, kindly disable it.

**Comment by lambert3** [comment]
Hey @RonKbS, there are some changes i made with the numbering in that object. The code i master also had duplicates of slope, elevation and some indicators were missing such as the 3 quaters of ndwi. Am sure the changes i made do work, i hope u take a closer look. However i will disable my linters.

**Comment by RonKbS** [comment]
> Hey @RonKbS, there are some changes i made with the numbering in that object. The code i master also had duplicates of slope, elevation and some indicators were missing such as the 3 quaters of ndwi. Am sure the changes i made do work, i hope u take a closer look. However i will disable my linters.

Sorry, I meant formatter. I think.
Ok. Let me take a closer look at that section.

**Comment by Geo-Gecko** [comment]
Changes merged from here -> https://github.com/Geo-Gecko/ASRT_GG/pull/19

**Pull request closed without merging**
